### ISSUE TITLE
La api no funsiona

### ISSUE THREAD

**Issue by Fucken33** [juanmartin1992/BurguerChat#2]
El controlador messageChatCtrl no esta usando las funciones de la api de express
router.get(uri, callback)
router.post(uri, callback)
...

**Comment by juanmartin1992** [comment]
El controlador messageChatCtrl contiene los métodos que se encargan de interactuar con los datos de la BD, quizas el error a sido llamarlo controlador en lugar de servicio, como lo verías, la rutas están en app.js

**Comment by Fucken33** [comment]
Entonces lo que falta es una ruta que use el controlador o servicio
Porque la linea "app.use('/api', messageChat)" espera un router de express.js en el segundo parametro.
Este router es el que tendria que contener las funciones antes citadas.
